## Alanna Cuddle Fuck Pre
label lbl_alanna_cuddle_fuck_pre:
    scene black
    with fade
    #"Developer Note: Art Assets not yet ready but H-scene is."
    pov "Alrighty, let's get this tub movin-"
    ala "Wait! Don't close the-"
    "{i}*Thud*{/i}"
    ala "-freezer... door..."
    pov "Uhm... Alanna?"
    pov "Don't tell me-"
    ala "Fuck!"
    pov "Isn't there a handle on the inside?"
    ala "It's fucking broken, [povname]."
    ala "It hasn't been working since I started working here."
    ala "I bet it hasn't been working even before me."
    pov "That sounds like a health and safety flaw."
    ala "Of course it's a health and safety flaw- we're fucking trapped in here."
    ala "Ughh- this happened to me a few months ago but lucky someone else was on the outside to let me out."
    ala "I'll need to call the manager, stupid fucking manager."
    ala "I told him about this so many fucking times."
    ala "{i}*Continues to grumble under her breath*{/i}"
    pov "Damn... it really does get cold in here fast- aye?"
    ala "Shut up- Hello! It's me, Alanna. Yeah, funny story."
    ala "You know how the walk-in freezer door is a one-way?"
    ala "Uh-huh- Uh-huh, yeah-yeah-yeah."
    ala "[povname] and I are locked in."
    ala "No one's manning the front."
    ala "..."
    ala "I can see how that's a problem for business."
    ala "Did I mention the walk-in freezer door is broken?"
    ala "..."
    ala "Right-"
    "{i}*Hang up beep*{/i}"
    ala "Yeah so, he's at an appointment at the moment, so he won't be here for like another hour."
    pov "An hour?! We're going to die in here."
    ala "No- no we're not."
    ala "We just-"
    ala "Have to stay warm."
    pov "How do you propose we do that, I'm already wearing two layers and my nuts are about to fall off."
    ala "Barry Grills says that the key to keeping warm is to insulate under yourself and use other's body heat."
    pov "Barry Grills told you this?"
    ala "In an episode..."
    ala "Anyway, we need to strip down; lay all our clothes under us; and spoon each other to keep our temperature up."
    ala "It's not going to work with fabric in between us."
    pov "That seems reeeeaaaally counter-intuitive."
    pov "To strip down in the cold?"
    ala "Just trust me, [povname]. Survival is not pretty."
    pov "Fuck me..."
    pov "And just a heads up, it's really cold in here so my buddy down there may not be at his best-"
    ala "[povname]! Shut the fuck up- I don't need you talking about that now."

    jump lbl_alanna_cuddle_fuck
