define audio.blowjob_a_01 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_01.ogg"
define audio.blowjob_a_02 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_02.ogg"
define audio.blowjob_a_03 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_03.ogg"
define audio.blowjob_a_04 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_04.ogg"
define audio.blowjob_a_05 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_05.ogg"
define audio.blowjob_a_06 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_06.ogg"
define audio.blowjob_a_07 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_07.ogg"
define audio.blowjob_a_08 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_08.ogg"
define audio.blowjob_a_09 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_A_09.ogg"
define audio.blowjob_b_01 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_01.ogg"
define audio.blowjob_b_02 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_02.ogg"
define audio.blowjob_b_03 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_03.ogg"
define audio.blowjob_b_04 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_04.ogg"
define audio.blowjob_b_05 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_05.ogg"
define audio.blowjob_b_06 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_06.ogg"
define audio.blowjob_b_07 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_07.ogg"
define audio.blowjob_b_08 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_08.ogg"
define audio.blowjob_b_09 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_B_09.ogg"
define audio.blowjob_c_01 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_C_01.ogg"
define audio.blowjob_c_02 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_C_02.ogg"
define audio.blowjob_c_03 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_C_03.ogg"
define audio.blowjob_c_04 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_C_04.ogg"
define audio.blowjob_c_05 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_C_05.ogg"
define audio.blowjob_c_06 = "ACTIONS/BLOWJOB/ACTIONS_BLOWJOB_C_06.ogg"

##############

define audio.body_collide_dressed_01 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_DRESSED_01.ogg"
define audio.body_collide_dressed_02 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_DRESSED_02.ogg"
define audio.body_collide_dressed_03 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_DRESSED_03.ogg"
define audio.body_collide_dressed_04 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_DRESSED_04.ogg"
define audio.body_collide_dressed_05 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_DRESSED_05.ogg"
define audio.body_collide_dressed_06 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_DRESSED_06.ogg"

define audio.body_collide_naked_01 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_01.ogg"
define audio.body_collide_naked_02 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_02.ogg"
define audio.body_collide_naked_03 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_03.ogg"
define audio.body_collide_naked_04 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_04.ogg"
define audio.body_collide_naked_05 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_05.ogg"
define audio.body_collide_naked_06 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_06.ogg"
define audio.body_collide_naked_07 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_07.ogg"
define audio.body_collide_naked_08 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_08.ogg"
define audio.body_collide_naked_09 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_09.ogg"
define audio.body_collide_naked_10 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_10.ogg"
define audio.body_collide_naked_11 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_11.ogg"
define audio.body_collide_naked_12 = "ACTIONS/BODY/COLLIDE/ACTIONS_BODY_COLLIDE_NAKED_12.ogg"

define audio.body_hit_hard_01 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_HARD_01.ogg"
define audio.body_hit_hard_02 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_HARD_02.ogg"
define audio.body_hit_hard_03 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_HARD_03.ogg"
define audio.body_hit_hard_04 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_HARD_04.ogg"
define audio.body_hit_hard_05 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_HARD_05.ogg"
define audio.body_hit_hard_06 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_HARD_06.ogg"
define audio.body_hit_soft_01 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_SOFT_01.ogg"
define audio.body_hit_soft_02 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_SOFT_02.ogg"
define audio.body_hit_soft_03 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_SOFT_03.ogg"
define audio.body_hit_soft_04 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_SOFT_04.ogg"
define audio.body_hit_soft_05 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_SOFT_05.ogg"
define audio.body_hit_soft_06 = "ACTIONS/BODY/HIT/ACTIONS_BODY_HIT_SOFT_06.ogg"

define audio.body_slap_hard_01 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_HARD_01.ogg"
define audio.body_slap_hard_02 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_HARD_02.ogg"
define audio.body_slap_hard_03 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_HARD_03.ogg"
define audio.body_slap_hard_04 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_HARD_04.ogg"
define audio.body_slap_hard_05 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_HARD_05.ogg"
define audio.body_slap_hard_06 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_HARD_06.ogg"
define audio.body_slap_soft_01 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_SOFT_01.ogg"
define audio.body_slap_soft_02 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_SOFT_02.ogg"
define audio.body_slap_soft_03 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_SOFT_03.ogg"
define audio.body_slap_soft_04 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_SOFT_04.ogg"
define audio.body_slap_soft_05 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_SOFT_05.ogg"
define audio.body_slap_soft_06 = "ACTIONS/BODY/SLAP/ACTIONS_BODY_SLAP_SOFT_06.ogg"

#########################

define audio.hands_grab_body_01 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_01.ogg"
define audio.hands_grab_body_02 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_02.ogg"
define audio.hands_grab_body_03 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_03.ogg"
define audio.hands_grab_body_04 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_04.ogg"
define audio.hands_grab_body_05 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_05.ogg"
define audio.hands_grab_body_06 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_06.ogg"
define audio.hands_grab_body_07 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_07.ogg"
define audio.hands_grab_body_08 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_08.ogg"
define audio.hands_grab_body_09 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_BODY_09.ogg"

define audio.hands_grab_clothes_01 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_01.ogg"
define audio.hands_grab_clothes_02 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_02.ogg"
define audio.hands_grab_clothes_03 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_03.ogg"
define audio.hands_grab_clothes_04 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_04.ogg"
define audio.hands_grab_clothes_05 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_05.ogg"
define audio.hands_grab_clothes_06 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_06.ogg"
define audio.hands_grab_clothes_07 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_07.ogg"
define audio.hands_grab_clothes_08 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_08.ogg"
define audio.hands_grab_clothes_09 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_CLOTHES_09.ogg"

define audio.hands_grab_hair_01 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_HAIR_01.ogg"
define audio.hands_grab_hair_02 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_HAIR_02.ogg"
define audio.hands_grab_hair_03 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_HAIR_03.ogg"
define audio.hands_grab_hair_04 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_HAIR_04.ogg"
define audio.hands_grab_hair_05 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_HAIR_05.ogg"
define audio.hands_grab_hair_06 = "ACTIONS/HANDS/GRAB/ACTIONS_HANDS_GRAB_HAIR_06.ogg"

define audio.hands_rub_body_01 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_BODY_01.ogg"
define audio.hands_rub_body_02 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_BODY_02.ogg"
define audio.hands_rub_body_03 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_BODY_03.ogg"
define audio.hands_rub_body_04 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_BODY_04.ogg"
define audio.hands_rub_body_05 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_BODY_05.ogg"
define audio.hands_rub_body_06 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_BODY_06.ogg"

define audio.hands_rub_clothes_01 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_CLOTHES_01.ogg"
define audio.hands_rub_clothes_02 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_CLOTHES_02.ogg"
define audio.hands_rub_clothes_03 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_CLOTHES_03.ogg"
define audio.hands_rub_clothes_04 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_CLOTHES_04.ogg"
define audio.hands_rub_clothes_05 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_CLOTHES_05.ogg"
define audio.hands_rub_clothes_06 = "ACTIONS/HANDS/RUB/ACTIONS_HANDS_RUB_CLOTHES_06.ogg"

###########################

define audio.mouth_french_kiss_01 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_01.ogg"
define audio.mouth_french_kiss_02 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_02.ogg"
define audio.mouth_french_kiss_03 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_03.ogg"
define audio.mouth_french_kiss_04 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_04.ogg"
define audio.mouth_french_kiss_05 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_05.ogg"
define audio.mouth_french_kiss_06 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_06.ogg"
define audio.mouth_french_kiss_07 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_07.ogg"
define audio.mouth_french_kiss_08 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_08.ogg"
define audio.mouth_french_kiss_09 = "ACTIONS/MOUTH/FRENCH_KISS/ACTIONS_MOUTH_FRENCH_KISS_09.ogg"

define audio.mouth_kiss_01 = "ACTIONS/MOUTH/KISS/ACTIONS_MOUTH_KISS_01.ogg"
define audio.mouth_kiss_02 = "ACTIONS/MOUTH/KISS/ACTIONS_MOUTH_KISS_02.ogg"
define audio.mouth_kiss_03 = "ACTIONS/MOUTH/KISS/ACTIONS_MOUTH_KISS_03.ogg"
define audio.mouth_kiss_04 = "ACTIONS/MOUTH/KISS/ACTIONS_MOUTH_KISS_04.ogg"
define audio.mouth_kiss_05 = "ACTIONS/MOUTH/KISS/ACTIONS_MOUTH_KISS_05.ogg"
define audio.mouth_kiss_06 = "ACTIONS/MOUTH/KISS/ACTIONS_MOUTH_KISS_06.ogg"

define audio.mouth_puff_01 = "ACTIONS/MOUTH/PUFF/ACTIONS_MOUTH_PUFF_01.ogg"
define audio.mouth_puff_02 = "ACTIONS/MOUTH/PUFF/ACTIONS_MOUTH_PUFF_02.ogg"
define audio.mouth_puff_03 = "ACTIONS/MOUTH/PUFF/ACTIONS_MOUTH_PUFF_03.ogg"
define audio.mouth_puff_04 = "ACTIONS/MOUTH/PUFF/ACTIONS_MOUTH_PUFF_04.ogg"
define audio.mouth_puff_05 = "ACTIONS/MOUTH/PUFF/ACTIONS_MOUTH_PUFF_05.ogg"
define audio.mouth_puff_06 = "ACTIONS/MOUTH/PUFF/ACTIONS_MOUTH_PUFF_06.ogg"

define audio.mouth_saliva_01 = "ACTIONS/MOUTH/SALIVA/ACTIONS_MOUTH_SALIVA_01.ogg"
define audio.mouth_saliva_02 = "ACTIONS/MOUTH/SALIVA/ACTIONS_MOUTH_SALIVA_02.ogg"
define audio.mouth_saliva_03 = "ACTIONS/MOUTH/SALIVA/ACTIONS_MOUTH_SALIVA_03.ogg"
define audio.mouth_saliva_04 = "ACTIONS/MOUTH/SALIVA/ACTIONS_MOUTH_SALIVA_04.ogg"
define audio.mouth_saliva_05 = "ACTIONS/MOUTH/SALIVA/ACTIONS_MOUTH_SALIVA_05.ogg"
define audio.mouth_saliva_06 = "ACTIONS/MOUTH/SALIVA/ACTIONS_MOUTH_SALIVA_06.ogg"

define audio.mouth_suck_01 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_01.ogg"
define audio.mouth_suck_02 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_02.ogg"
define audio.mouth_suck_03 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_03.ogg"
define audio.mouth_suck_04 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_04.ogg"
define audio.mouth_suck_05 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_05.ogg"
define audio.mouth_suck_06 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_06.ogg"
define audio.mouth_suck_07 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_07.ogg"
define audio.mouth_suck_08 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_08.ogg"
define audio.mouth_suck_09 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_09.ogg"
define audio.mouth_suck_10 = "ACTIONS/MOUTH/SUCK/ACTIONS_MOUTH_SUCK_10.ogg"

define audio.mouth_swallow_01 = "ACTIONS/MOUTH/SWALLOW/ACTIONS_MOUTH_SWALLOW_01.ogg"
define audio.mouth_swallow_02 = "ACTIONS/MOUTH/SWALLOW/ACTIONS_MOUTH_SWALLOW_02.ogg"
define audio.mouth_swallow_03 = "ACTIONS/MOUTH/SWALLOW/ACTIONS_MOUTH_SWALLOW_03.ogg"
define audio.mouth_swallow_04 = "ACTIONS/MOUTH/SWALLOW/ACTIONS_MOUTH_SWALLOW_04.ogg"
define audio.mouth_swallow_05 = "ACTIONS/MOUTH/SWALLOW/ACTIONS_MOUTH_SWALLOW_05.ogg"
define audio.mouth_swallow_06 = "ACTIONS/MOUTH/SWALLOW/ACTIONS_MOUTH_SWALLOW_06.ogg"

######################################

define audio.penetration_a_01 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_01.ogg"
define audio.penetration_a_02 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_02.ogg"
define audio.penetration_a_03 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_03.ogg"
define audio.penetration_a_04 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_04.ogg"
define audio.penetration_a_05 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_05.ogg"
define audio.penetration_a_06 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_06.ogg"
define audio.penetration_a_07 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_07.ogg"
define audio.penetration_a_08 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_08.ogg"
define audio.penetration_a_09 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_A_09.ogg"
define audio.penetration_b_01 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_01.ogg"
define audio.penetration_b_02 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_02.ogg"
define audio.penetration_b_03 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_03.ogg"
define audio.penetration_b_04 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_04.ogg"
define audio.penetration_b_05 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_05.ogg"
define audio.penetration_b_06 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_06.ogg"
define audio.penetration_b_07 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_07.ogg"
define audio.penetration_b_08 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_08.ogg"
define audio.penetration_b_09 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_B_09.ogg"
define audio.penetration_c_01 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_01.ogg"
define audio.penetration_c_02 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_02.ogg"
define audio.penetration_c_03 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_03.ogg"
define audio.penetration_c_04 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_04.ogg"
define audio.penetration_c_05 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_05.ogg"
define audio.penetration_c_06 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_06.ogg"
define audio.penetration_c_07 = "ACTIONS/PENETRATION/ACTIONS_PENETRATION_C_07.ogg"

#################

define audio.penis_cum_01 = "ACTIONS/PENIS/ACTIONS_PENIS_CUM_01.ogg"
define audio.penis_cum_02 = "ACTIONS/PENIS/ACTIONS_PENIS_CUM_02.ogg"
define audio.penis_cum_03 = "ACTIONS/PENIS/ACTIONS_PENIS_CUM_03.ogg"
define audio.penis_cum_04 = "ACTIONS/PENIS/ACTIONS_PENIS_CUM_04.ogg"
define audio.penis_cum_05 = "ACTIONS/PENIS/ACTIONS_PENIS_CUM_05.ogg"
define audio.penis_cum_06 = "ACTIONS/PENIS/ACTIONS_PENIS_CUM_06.ogg"

define audio.penis_handjob_01 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_01.ogg"
define audio.penis_handjob_02 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_02.ogg"
define audio.penis_handjob_03 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_03.ogg"
define audio.penis_handjob_04 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_04.ogg"
define audio.penis_handjob_05 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_05.ogg"
define audio.penis_handjob_06 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_06.ogg"
define audio.penis_handjob_07 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_07.ogg"
define audio.penis_handjob_08 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_08.ogg"
define audio.penis_handjob_09 = "ACTIONS/PENIS/ACTIONS_PENIS_HANDJOB_09.ogg"

###########################

define audio.vagina_insertion_a_01 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_01.ogg"
define audio.vagina_insertion_a_02 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_02.ogg"
define audio.vagina_insertion_a_03 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_03.ogg"
define audio.vagina_insertion_a_04 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_04.ogg"
define audio.vagina_insertion_a_05 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_05.ogg"
define audio.vagina_insertion_a_06 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_06.ogg"
define audio.vagina_insertion_a_07 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_A_07.ogg"
define audio.vagina_insertion_b_01 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_01.ogg"
define audio.vagina_insertion_b_02 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_02.ogg"
define audio.vagina_insertion_b_03 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_03.ogg"
define audio.vagina_insertion_b_04 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_04.ogg"
define audio.vagina_insertion_b_05 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_05.ogg"
define audio.vagina_insertion_b_06 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_06.ogg"
define audio.vagina_insertion_b_07 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_07.ogg"
define audio.vagina_insertion_b_08 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_08.ogg"
define audio.vagina_insertion_b_09 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_09.ogg"
define audio.vagina_insertion_b_10 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_10.ogg"
define audio.vagina_insertion_b_11 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_11.ogg"
define audio.vagina_insertion_b_12 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_B_12.ogg"
define audio.vagina_insertion_c_01 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_C_01.ogg"
define audio.vagina_insertion_c_02 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_C_02.ogg"
define audio.vagina_insertion_c_03 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_C_03.ogg"
define audio.vagina_insertion_c_04 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_C_04.ogg"
define audio.vagina_insertion_c_05 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_C_05.ogg"
define audio.vagina_insertion_c_06 = "ACTIONS/VAGINA/INSERTION/ACTIONS_VAGINA_INSERTION_C_06.ogg"

define audio.vagina_queff_01 = "ACTIONS/VAGINA/QUEFF/ACTIONS_VAGINA_QUEFF_01.ogg"
define audio.vagina_queff_02 = "ACTIONS/VAGINA/QUEFF/ACTIONS_VAGINA_QUEFF_02.ogg"
define audio.vagina_queff_03 = "ACTIONS/VAGINA/QUEFF/ACTIONS_VAGINA_QUEFF_03.ogg"
define audio.vagina_queff_04 = "ACTIONS/VAGINA/QUEFF/ACTIONS_VAGINA_QUEFF_04.ogg"
define audio.vagina_queff_05 = "ACTIONS/VAGINA/QUEFF/ACTIONS_VAGINA_QUEFF_05.ogg"
define audio.vagina_queff_06 = "ACTIONS/VAGINA/QUEFF/ACTIONS_VAGINA_QUEFF_06.ogg"

define audio.vagina_squirt_long_01 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_01.ogg"
define audio.vagina_squirt_long_02 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_02.ogg"
define audio.vagina_squirt_long_03 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_03.ogg"
define audio.vagina_squirt_long_04 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_04.ogg"
define audio.vagina_squirt_long_05 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_05.ogg"
define audio.vagina_squirt_long_06 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_06.ogg"
define audio.vagina_squirt_long_07 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_07.ogg"
define audio.vagina_squirt_long_08 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_08.ogg"
define audio.vagina_squirt_long_09 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_LONG_09.ogg"

define audio.vagina_squirt_short_01 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_SHORT_01.ogg"
define audio.vagina_squirt_short_02 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_SHORT_02.ogg"
define audio.vagina_squirt_short_03 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_SHORT_03.ogg"
define audio.vagina_squirt_short_04 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_SHORT_04.ogg"
define audio.vagina_squirt_short_05 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_SHORT_05.ogg"
define audio.vagina_squirt_short_06 = "ACTIONS/VAGINA/SQUIRT/ACTIONS_VAGINA_SQUIRT_SHORT_06.ogg"

define audio.vagina_touch_01 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_01.ogg"
define audio.vagina_touch_02 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_02.ogg"
define audio.vagina_touch_03 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_03.ogg"
define audio.vagina_touch_04 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_04.ogg"
define audio.vagina_touch_05 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_05.ogg"
define audio.vagina_touch_06 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_06.ogg"
define audio.vagina_touch_07 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_07.ogg"
define audio.vagina_touch_08 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_08.ogg"
define audio.vagina_touch_09 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_09.ogg"
define audio.vagina_touch_10 = "ACTIONS/VAGINA/TOUCH/ACTIONS_VAGINA_TOUCH_10.ogg"

############################
